# Generated by Django 4.2.1 on 2023-05-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('subtitle', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='banners')),
                ('active', models.BooleanField()),
                ('button', models.URLField(null=True)),
            ],
            options={
                'verbose_name': 'Banners',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
