# Generated by Django 4.2.1 on 2023-05-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_rename_select_parent_menuitem_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='button',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
