# Generated by Django 4.2.1 on 2023-05-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_menuitem_options_alter_banner_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button',
            field=models.SlugField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.SlugField(default='', max_length=200, null=True),
        ),
    ]
