# Generated by Django 4.2.1 on 2023-05-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_mainpagesections_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpagesections',
            options={'ordering': ['order'], 'verbose_name': 'Page Section', 'verbose_name_plural': 'Page Sections'},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='button_CTA',
            new_name='button_link',
        ),
        migrations.RenameField(
            model_name='mainpagesections',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainpagesections',
            name='button_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainpagesections',
            name='button_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainpagesections',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mainpagesections',
            name='type',
            field=models.CharField(choices=[('SHOP', 'Shop'), ('GALLERY', 'Gallery'), ('PORTFOLIO', 'Portfolio')], max_length=200, null=True),
        ),
    ]
