# Generated by Django 4.2.1 on 2023-05-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_mainpagesections_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagesections',
            name='button_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mainpagesections',
            name='button_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
