# Generated by Django 4.2.1 on 2023-05-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_age_remove_event_name_event_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Events',
        ),
    ]
