# Generated by Django 4.2.1 on 2023-05-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_event_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
