# Generated by Django 4.2.1 on 2023-05-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_socialmedia_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='WishlistItem',
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'verbose_name_plural': 'Wishlist'},
        ),
    ]
