# Generated by Django 4.2.1 on 2023-05-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_rename_wishlist_wishlistitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMedia',
            new_name='SocialMediaLink',
        ),
    ]
