# Generated by Django 4.2.1 on 2023-05-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_alter_event_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
