# Generated by Django 4.2.1 on 2023-05-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_wishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
    ]
