# Generated by Django 4.2.1 on 2023-05-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_rename_title_event_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={'verbose_name': 'Social Media', 'verbose_name_plural': 'Social Media'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'verbose_name': 'Wishlist', 'verbose_name_plural': 'Wishlist'},
        ),
    ]
