# Generated by Django 4.2.1 on 2023-05-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0010_affiliatelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatelink',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
